language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="dh-systemd libaccountsservice-dev libglib2.0-dev libgranite-dev libgtk-3-dev libpolkit-gobject-1-dev libswitchboard-2.0-dev libdbus-1-dev libsystemd-dev meson valac"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"

script:
 - echo BUILDS PASSED
